- name: Create SPC namespace
  kubernetes.core.k8s:
    state: present
    namespace: sagasrv-spc
    kubeconfig: "{{ kubeconfig_file }}"

- name: Deploy SPC LB
  kubernetes.core.k8s:
    state: present
    template: templates/spc-lb.yml.j2
    kubeconfig: "{{ kubeconfig_file }}"
  register: spc_lb
  when: expose_p2p

- name: Get public IP from SPC LB
  kubernetes.core.k8s_info:
    kind: Service
    name: spc-public
    namespace: sagasrv-spc
    wait: true
    kubeconfig: "{{ kubeconfig_file }}"
  until: (svc_info['resources'][0]['status']['loadBalancer']['ingress'][0]['ip'] | default('')) != ''
  retries: 10
  delay: 5
  register: svc_info
  when: expose_p2p

- name: Set SPC public address or localhost
  set_fact:
    spc_external_address: "{{ svc_info['resources'][0]['status']['loadBalancer']['ingress'][0]['ip'] if expose_p2p else '127.0.0.1' }}"

- name: Deploy SPC
  kubernetes.core.k8s:
    state: present
    template: templates/spc-deploy.yml.j2
    kubeconfig: "{{ kubeconfig_file }}"