# ethproxy (disabled by default)
ethproxy_enabled: false
ethproxy_version: "0.6.4"
ethproxy_resources:
  requests:
    cpu: "2"
    memory: "4Gi"
  limits:
    cpu: "4"
    memory: "8Gi"
ethproxy_replicas: 1

# List of chainlets to manage ethproxy resources for.
# Each entry must contain:
#   - namespace: <k8s namespace>
#   - ethproxy_version: <ethproxy version>
#   - ethproxy_replicas: <ethproxy replicas>
#   - rate_limit_enabled: <rate limit enabled>
#   - whitelist_accounts: <whitelist accounts>
#   - node_rpc: <node rpc>
#   - node_json_rpc: <node json rpc>
#   - chain_id: <chain id>
#   - broadcast_node_rpc: <broadcast node rpc>
ethproxy_configs: []
