# Ansible
ansible_connection: local
ansible_host: 127.0.0.1

# Chainlets
loglevel: info
stake_amount: 1500000
staking_fees: 100000

# Snapshots
snapshot_enabled: true
snapshot_interval: 1000
snapshot_keep_recent: 2

# StateSync
statesync_trust_interval: 1000
statesync_enabled: false
statesync_rpc_domains:

# Fluentd
fluentd_enabled: false
