# Chainlets
s3_bucket: s3://testnet-prod-v2
quorum_count: 4
validator_addresses: saga1atjuvcf4aq3upr5eacacpv08lkp39v8208gw6z saga12uch6j240eqv5zgpr4f4zyy4c3gf923ky9qyru saga1hvm67hnpmfc5pfpeqqmung4kjqcavzatjegxu9 saga16rga04jaj3qsfwcm8w3m9hupx828k3lshzpz2j
stake_owner_address: saga162k9aqdgagr6qwjugqaktfycaechhnpzgl3rgs
foundation_wallet_address: saga1u2a8ktctqhpx655ysw7ru27t6hqt9wlq4fn5ca
is_testnet: true
controller_chainlet_pvc_size: "50Gi"
hub_chain_id: hub_5464111-1

# Enabled components
expose_p2p: true
metrics_enabled: true
statesync_enabled: true
metrics_alertmanager_enabled: true

# StateSync
statesync_rpc_domains:
  - stsrv1.sagarpc.io
  - st1.sagarpc.io

# SSC (disabled by default for testnet)
ssc_chain_id: "ssc-testnet-3"
ssc_denom: "utsaga"
ssc_consumer_gas_price: "0.01"
ssc_genesis_url: "https://raw.githubusercontent.com/sagaxyz/testnet-3/refs/heads/main/config/genesis.json"
ssc_volume_size: "25Gi"
ssc_rpc_servers:
  - https://testnet2-keplr.sagarpc.io:443
  - https://testnet2-keplr.sagarpc.io:443
ssc_peers: "4cbd2ae71e1cd58d64568a95a7f24d0bdf86cb83@184.107.182.148:57600,c9377aab40b7361c1705dfdf4526035ecfa9518c@65.21.111.137:26656,1686f61de8fffce1cb93b51783aa1ddfd06302b6@93.115.24.179:26656,72740e63a77dbadd69036bc8fcef7c8fe6950d12@65.21.220.178:26656,9d15565cbef6e1f630e8875ac358dee42f4530eb@80.64.208.45:26656,cff377766a8291d55948d399a6bd5d8f17fef802@saga-testnet-p2p-0.tm.p2p.world:26656"
